### ISSUE TITLE
Angle on Linux

### ISSUE THREAD

**Issue by Nathan-MV** [Admenri/rguplayer#11]
It appears that it is unable to detect the ``.so`` related to Angle (tested putting it in ANGLE/amd64, ANGLE/i32 and in the root folder), i was trying to test running Angle with Vulkan on Linux

**Comment by Admenri** [comment]
I'm not familiar with how to set up ANGLE under Linux. If you have any ideas, you can pull request.

**Comment by Nathan-MV** [comment]
It seems it was not limited to Linux, the latest Windows build is also affected
