### ISSUE TITLE
[改造] 引擎现代化改造 - 更新清单

### ISSUE THREAD

**Issue by Admenri** [Admenri/rguplayer#14]
The Universal Ruby Game Engine 现代化改造列表：
2024.7.24拟定

1. 更新全新设置读写机制，包括：
放弃读取ini，使用json读取配置，
自动检查RGSS版本：通过检查是否含有文件：Data/Scripts.rvdata (2)

2. 对content层导出类（Sprite Plane等）解耦，
放弃内置的GLES 3.0渲染器，改用第三方图形接口，
全面翻新渲染线程，改用现代图形API规范实现图像部分：
内置shader由GLSL ES标准转换为类似GLSL的语言
由GLES通过ANGLE转译到D3D11，Vulkan后端
转向非转译模式的D3D11，D3D12，Vulkan后端。
在移动端支持非转译的Vulkan后端

导出功能变化：
需要提供批量绘制几何图形的类Geometry
需要重新设计Shader类以适应现代图形API的设计

3. （待定）放弃使用SoLoud库作为音频部分核心解码器，
使用OpenAL + stb, dr库等实现相同效果

4. 通过Ruby 3.0引入的FiberScheduler实现BoostASIO库封装
以达到支持异步IO的效果

5. （待定）研究一种新型加密格式，需要散步在程序里的几个密钥解码
用户可以通过为exe设置VMP加壳等方式实现强加密

6. 绑定层提供一套常用的Win32API内置功能（ini读写，内存操作等）
用于补齐Win32API跨平台需求

7. 在改造完成图形API的基础上提供Spine2D的支持
（待定）提供Native Live2D Cubism支持

8. 将静态链接的Ruby库更改为动态链接
以支持require 'xxx.so'的操作
间接实现支持Ruby Gem库

9. 将content层引入协程调度，协调event_loop和render过程
用于将引擎的多线程架构协调为协程单线程运行模式来移植到web平台

**Comment by Admenri** [comment]
创建新的分支legacy-rgu用于继续维护RGU的旧版本，
同时设置主分支master为现代化改造分支

**Comment by R-YaTian** [comment]
请问作者，关于第六点，有计划支持调用Windows动态库中的Api么，便于开发者使用自行开发的动态库进行win平台上的扩展

**Comment by Admenri** [comment]
> 请问作者，关于第六点，有计划支持调用Windows动态库中的Api么，便于开发者使用自行开发的动态库进行win平台上的扩展

不会提供完整win32api支持，但是会提供一些常用的api内置在绑定层

**Comment by Admenri** [comment]
使用现代图形后端与协程调度，支持web端的URGE现已开始开发：
本项目转为LTSC版本提供长期维护，不再增加新功能
https://github.com/Admenri/urge
