### ISSUE TITLE
Missing Code in Repository

### ISSUE THREAD

**Issue by Nathan-MV** [Admenri/rguplayer#2]
It seems like everything related to Audio/Input is not in the repository?

**Comment by Admenri** [comment]
During the development stage, the priority of the Input and Audio modules is set after Graphics. The initial version is expected to be completed around the Chinese New Year.

**Comment by Nathan-MV** [comment]
> During the development stage, the priority of the Input and Audio modules is set after Graphics. The initial version is expected to be completed around the Chinese New Year.

I said missing because RGU build from
https://rpg.blue/thread-486473-1-1.html
seem to have
