### ISSUE TITLE
Reference from other functional RGSS implementations

### ISSUE THREAD

**Issue by Nathan-MV** [Admenri/rguplayer#3]
# C++ SDL2 
Most complete:
https://github.com/mkxp-z/mkxp-z
https://github.com/thehatkid/mkxp-z-android

Uses some fancy libraries: 
https://github.com/gxm11/RGModern

# C++ SFML
It is divided into LiteRGSS2 and LiteCGSS:
https://gitlab.com/pokemonsdk/litergss2
https://gitlab.com/NuriYuri/litecgss

https://github.com/Scorbutics/litergss-android

# Unmaintained below

# C
https://github.com/qnighy/tapir

# Java libgdx
https://github.com/CameraBroke/JRGSS/tree/glrw

# Ruby SDL
https://github.com/zh99998/OpenRGSS
https://github.com/zh99998/OpenRGSS-RPGMaker

**Comment by Admenri** [comment]
Since mkxp is under the GPL license, I won't dwell on that. The original RGU, which I wrote during high school, was too messy in structure, so I didn't open source it. Now that I have some time, I've decided to refactor the architecture. The plan is to write it in an asynchronous multithreaded mode. As for referencing RGM, I actually know the author of RGM, and the inspiration for asynchronous multithreading came from him. Considering that I also have another commercial project to maintain, I will only maintain this project sporadically.

**Comment by Nathan-MV** [comment]
The developer of LiteRGSS2 said at some point that he implemented SpriteMap in C++, tilemap uses SpriteMap, which is a collection of Sprite objects, but exposes only one sprite in the ruby world, which makes z-sorting faster because you divide the number of sprite needed by 22 with this optimization

**Comment by Admenri** [comment]
There is a reason for not using third-party graphics libraries. My plan is for RGU to support extensible plugins, with upcoming plugins for Live2D and Spine. These third-party libraries directly invoke the OGL graphics API. Simultaneously, creating a custom rendering process allows for better optimization of the draw call flow. Additionally, the new RGU is planned to be cross-platform. The cross-platform behavior of third-party libraries is challenging to accurately predict and control. Therefore, the optimal solution, considering these factors, is to write the rendering part ourselves.

**Comment by Nathan-MV** [comment]
> There is a reason for not using third-party graphics libraries. My plan is for RGU to support extensible plugins, with upcoming plugins for Live2D and Spine. These third-party libraries directly invoke the OGL graphics API. Simultaneously, creating a custom rendering process allows for better optimization of the draw call flow. Additionally, the new RGU is planned to be cross-platform. The cross-platform behavior of third-party libraries is challenging to accurately predict and control. Therefore, the optimal solution, considering these factors, is to write the rendering part ourselves.

I'm not saying that RGU would be better with Raylib, i was just expressing my thoughts because Raylib is the de facto low-maintenance cross-compatible for Windows, macOS, Linux, ChromeOS, FreeBSD, Raspberry PI, Android, Web and has everything that RGSS uses already implemented in it by default, and its popularity on github is only below Godot's
