### ISSUE TITLE
Sprite Drawing Benchmark

### ISSUE THREAD

**Issue by Nathan-MV** [Admenri/rguplayer#4]
As it is still in development, it may help you, LiteRGSS2 seems to be the fastest of the bunch for now
| Engine        | Sprites | Frames per Second |
| ------------- | ------------- | ------------------------ |
| MKXP-Z        | 20,000        | 34                       |
| RGM     | 50,000        | 33|
| LiteRGSS2     | 50,000        | 47                       |

```
class SpriteGenerator
  DEFAULT_SPRITE_COUNT = 20_000
  SCREEN_WIDTH = 640
  SCREEN_HEIGHT = 480
  SPRITE_SIZE = 32

  def initialize
    @sprite_count = DEFAULT_SPRITE_COUNT
    @viewport = Viewport.new(0, 0, SCREEN_WIDTH, SCREEN_HEIGHT)
    @bitmap = nil
  end

  def run
    initialize_sprites
    loop do
      Graphics.update
    end
  rescue StandardError
    puts "\nEND\n"
  end

  private

  def initialize_sprites
    puts "Sprite Count: #{@sprite_count}"

    @sprites = @sprite_count.times.map do |i|
      initialize_bitmap if (i % 100).zero?
      initialize_sprite
    end
  end

  def initialize_bitmap
    @bitmap = Bitmap.new(320, 320)
    @bitmap.fill_rect(0, 0, 320, 320, random_color)
  end

  def initialize_sprite
    sprite = Sprite.new(@viewport)
    sprite.bitmap = @bitmap
    sprite.x = rand(SCREEN_WIDTH) - SPRITE_SIZE
    sprite.y = rand(SCREEN_HEIGHT) - SPRITE_SIZE
    set_sprite_src_rect(sprite)
    sprite
  end

  def set_sprite_src_rect(sprite)
    j = @sprite_count % 100
    sprite.src_rect.set(32 * (j / 10), 32 * (j % 10), SPRITE_SIZE, SPRITE_SIZE)
  end

  def random_color
    Color.new(rand(256), rand(256), rand(256), 32)
  end
end

SpriteGenerator.new.run
```

**Comment by Admenri** [comment]
Thank you for the test code. I tested it with my 3050 graphics card, and it can run 20,000 sprites at a full 60 FPS, but drops to about 30 FPS with 50,000 sprites. However, I don't plan to pursue extremely high performance since my time is limited, so I might lean more towards compatibility and extensibility.

**Comment by Nathan-MV** [comment]
Updated my benchmarks
```
mkxp-z can draw 10k at 26 fps, with YJIT it can draw 20k at 34 fps (YJIT was tested with Linux)
mkxp-z with Angle (Direct3D) can draw 10k at 39 fps and Angle (Vulkan) at 44 fps (Not tested with YJIT)

RGD can draw 10k at 39 fps, with batch drawing it can draw 10k at 49 fps (RGD 1.5.4 is faster than the experimental 1.6.1)
RGU with any Angle options can draw 10k at 19 fps (The new build released a day ago)
RGM can draw 50k with 33 fps

LiteRGSS2 can draw 60k at 42 fps
```

I assume that RGM performance at it is because of Centurion? (I mean everything is just using SDL2 minus LiteRGSS2)
https://github.com/albin-johansson/centurion
YJIT is just a matter of using `--yjit` to start Ruby, but only works on MacOS and Linux

**Comment by Nathan-MV** [comment]
On the latest release, this benchmark is only capable of drawing 2k sprites at 60 FPS, the same as RGSS3 Game.exe

**Comment by Admenri** [comment]
> On the latest release, this benchmark is only capable of drawing 2k sprites at 60 FPS, the same as RGSS3 Game.exe

Oh, the renderer does not batch sprites. Although the benchmark scores might be lower, the actual performance in the game is  good (an action game on steam is using the engine).
I have marked the 1.0 version branch using OpenGL as legacy. The current 2.0 version branch uses the native graphics APIs of bgfx's D3D12/Vulkan, which should significantly improve performance.

**Comment by Admenri** [comment]
The development of URGE, utilizing modern graphics backends and coroutine scheduling with web support, has now begun. This project will be converted to an LTSC version for long-term maintenance, and no new features will be added.
https://github.com/Admenri/urge
