### ISSUE TITLE
[Feature] Zig Compiler

### ISSUE THREAD

**Issue by Nathan-MV** [Admenri/rguplayer#5]
I'm tired of using XCode for Mac builds... as it's still in development you could aim for Zig cross compiler
https://medium.com/@edlyuu/zig-c-c-compiler-wtf-is-zig-c-790d9ad8d85b

**Comment by Admenri** [comment]
Currently, this engine has completed the Graphics and Input parts for RGSS2 and RGSS3. The Filesystem and Audio parts remain unfinished. Moreover, I have actually been using Visual Studio's solution (sln) for build management, so I plan to delegate this feature to someone else. Thank you for your suggestion.

**Comment by Admenri** [comment]
The development of URGE, utilizing modern graphics backends and coroutine scheduling with web support, has now begun. This project will be converted to an LTSC version for long-term maintenance, and no new features will be added.
https://github.com/Admenri/urge
