### ISSUE TITLE
[Feature] Geometry API Extension

### ISSUE THREAD

**Issue by Nathan-MV** [Admenri/rguplayer#9]
After reviewing common extensions to the Bitmap class, it's evident that shapes such as lines, circles, triangles, polygons, isogons, and ellipses are frequently added. As RGU already includes a Geometry class, extending it to handle common geometry shapes beyond just triangles seems beneficial.

- [ ] Line
- [ ] Circle
- [ ] Polygon
- [ ] Isogon
- [ ] Ellipse

**Comment by Admenri** [comment]
The development of URGE, utilizing modern graphics backends and coroutine scheduling with web support, has now begun. This project will be converted to an LTSC version for long-term maintenance, and no new features will be added.
https://github.com/Admenri/urge
